/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcb_shdl_CommThread */

#ifndef _Included_org_jcb_shdl_CommThread
#define _Included_org_jcb_shdl_CommThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jcb_shdl_CommThread
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcb_shdl_CommThread_init
  (JNIEnv *, jclass);

/*
 * Class:     org_jcb_shdl_CommThread
 * Method:    openData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcb_shdl_CommThread_openData
  (JNIEnv *, jclass);

/*
 * Class:     org_jcb_shdl_CommThread
 * Method:    closeData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcb_shdl_CommThread_closeData
  (JNIEnv *, jclass);

/*
 * Class:     org_jcb_shdl_CommThread
 * Method:    writeByte
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jcb_shdl_CommThread_writeByte
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jcb_shdl_CommThread
 * Method:    readByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jcb_shdl_CommThread_readByte
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
